-- MySQL Script generated by MySQL Workbench
-- 02/14/15 08:58:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sokobandb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sokobandb` ;
DROP DATABASE IF EXISTS `sokobandb`;

-- -----------------------------------------------------
-- Schema sokobandb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sokobandb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sokobandb` ;
CREATE DATABASE `sokobandb` /*!40100 DEFAULT CHARACTER SET utf8 */;

-- -----------------------------------------------------
-- Table `sokobandb`.`Spelers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sokobandb`.`Spelers` ;

CREATE TABLE IF NOT EXISTS `sokobandb`.`Spelers` (
  `gebruikersnaam` VARCHAR(45) NOT NULL,
  `wachtwoord` VARCHAR(45) NOT NULL,
  `adminrechten` TINYINT(1) NOT NULL,
  `voornaam` VARCHAR(45),
  `achternaam` VARCHAR(45),
  PRIMARY KEY (`gebruikersnaam`),
  UNIQUE INDEX `gebruikersnaam_UNIQUE` (`gebruikersnaam` ASC))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;